CryptoHubV2/CryptoHub/Models/ErrorViewModel.cs
namespace CryptoHub.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CryptoHubV2/CryptoHub/Models/Portfolio.cs
using CoinGecko.Entities.Response.Coins;
using CoinGecko.Entities.Response.Simple;

namespace CryptoHub.Models
{
    public class Portfolio
    {
        public Price CryptoPrice { get; set; }
        public IReadOnlyList<CoinList> CryptoList { get; set; }
    }
}

CryptoHubV2/CryptoHub/Controllers/CoinController.cs
using CoinGecko.Clients;
using CoinGecko.Entities.Response.Coins;
using CoinGecko.Entities.Response.Search;
using CryptoHub.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.IdentityModel.Tokens;

namespace CryptoHub.Controllers;

public class CoinController : Controller
{
    private readonly CoinService _service;
    public CoinController(CoinService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index(string? id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            return NotFound();
        }

        var res = await _service.GetCoinDataByIdAsync(id);

        if (res == null)
        {
            return NotFound();
        }

        return View(res);
    }

    // Trending coins /Coin/Trending
    public async Task<IActionResult> Trending()
    {
        var res = await _service.GetTrendingCoinsListAsync();

        return View("TrendingCoins", res);
    }

    // Live Market --- /Coin/Market
    public async Task<IActionResult> Market()
    {
        var res = await _service.GetMarketDataAsync();

        return View("Market", res);
    }

    // Search coin /Coin/Search
    public async Task<IActionResult> Search(string? searchString)
    {
        var res = await _service.GetCoinListAsync();

        if (string.IsNullOrWhiteSpace(searchString))
        {
            return View("Search", res);
        }

        res = res.Where(r => r.Name.ToLower().Contains(searchString.ToLower())).ToList().AsReadOnly();

        return View("Search", res);
    }

    // Search Coin /Coin/Coindata
    public async Task<IActionResult> CoinData(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            return NotFound();
        }

        var res = await _service.GetCoinDataByIdAsync(id);

        if (res == null)
        {
            return NotFound();
        }

        return View("CoinData", res);
        
    }

}

CryptoHubV2/CryptoHub/Controllers/CryptoController.cs
using CoinGecko.Clients;
using CoinGecko.Entities.Response.Coins;
using CoinGecko.Entities.Response.Search;
using CryptoHub.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.IdentityModel.Tokens;

namespace CryptoHub.Controllers;

public class CryptoController : Controller
{
    private readonly CryptoService _service;
    public CryptoController(CryptoService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index(string? id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            return NotFound();
        }

        var res = await _service.GetCoinDataByIdAsync(id);

        if (res == null)
        {
            return NotFound();
        }

        return View(res);
    }

    // Trending coins /Crypto/Trending
    public async Task<IActionResult> Trending()
    {
        var res = await _service.GetTrendingCoinsListAsync();

        return View("TrendingCoins", res);
    }

    // Live Market --- /Crypto/Market
    public async Task<IActionResult> Market()
    {
        var res = await _service.GetMarketDataAsync();

        return View("Market", res);
    }

    // Search Crypto /Crypto/Search
    public async Task<IActionResult> Search(string? searchString)
    {
        var res = await _service.GetCoinListAsync();

        if (string.IsNullOrWhiteSpace(searchString))
        {
            return View("Search", res);
        }

        res = res.Where(r => r.Name.ToLower().Contains(searchString.ToLower())).ToList().AsReadOnly();

        return View("Search", res);
    }

    // Search Crypto /Crypto/Cryptodata
    public async Task<IActionResult> CryptoData(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            return NotFound();
        }

        var res = await _service.GetCoinDataByIdAsync(id);

        if (res == null)
        {
            return NotFound();
        }

        return View("CryptoData", res);    
    }

    
    public async Task<IActionResult> Portfolio()
    {
        var res = await _service.PortfolioGeneratorAsync();
        return View("Portfolio", res);
    }

}

CryptoHubV2/CryptoHub/Controllers/HomeController.cs
using CryptoHub.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CryptoHub.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CryptoHubV2/CryptoHub/Views/Coin/CoinData.cshtml
@using System.Globalization;
@model CoinGecko.Entities.Response.Coins.CoinFullDataById

@{
    ViewData["Title"] = Model.Name;
}

<div class="jumbotron text-center">
    <h1 class="display-4"><img class="rounded-circle" src="@Model.Image.Small" /> @Html.DisplayName(Model.Name) (@Html.DisplayName(Model.Symbol.ToUpper()))</h1>
    <p class="lead">Last Updated: @Html.DisplayName(Model.MarketData.LastUpdated.Value.ToString("f", CultureInfo.CreateSpecificCulture("en-US"))) (GMT)</p>
    <hr />
</div>

<div class="row">
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-pencil primary font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            @if (Model.MarketCapRank != null)
                            {
                                <h3>@Html.DisplayFor(model => model.MarketCapRank)</h3>

                            }
                            else
                            {
                                <h3>N/A</h3>
                            }
                            <span>Market Rank</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            <h3>$@Html.DisplayName(Model.MarketData.CurrentPrice.GetValueOrDefault("usd").ToString())</h3>
                            <span>Current Price</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            <h3>$@Html.DisplayName(Model.MarketData.High24H.GetValueOrDefault("usd").ToString())</h3>
                            <span>High 24h</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            <h3>$@Html.DisplayName(Model.MarketData.Low24H.GetValueOrDefault("usd").ToString())</h3>
                            <span>Low 24h</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            @if (Model.MarketData.PriceChangePercentage24H < 0)
                            {
                                <h3 class="text-danger">@Html.DisplayFor(model => model.MarketData.PriceChangePercentage24H)</h3>

                            }
                            else
                            {
                                <h3 class="text-success">@Html.DisplayFor(model => model.MarketData.PriceChangePercentage24H)</h3>

                            }
                            <span>24h %</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            @if (Decimal.Parse(Model.MarketData.PriceChangePercentage7D) < 0)
                            {
                                <h3 class="text-danger">@Html.DisplayFor(model => model.MarketData.PriceChangePercentage7D)</h3>

                            }
                            else
                            {
                                <h3 class="text-success">@Html.DisplayFor(model => model.MarketData.PriceChangePercentage7D)</h3>

                            }
                            <span>7d %</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            @if (Decimal.Parse(Model.MarketData.PriceChangePercentage30D) < 0)
                            {
                                <h3 class="text-danger">@Html.DisplayFor(model => model.MarketData.PriceChangePercentage30D)</h3>

                            }
                            else
                            {
                                <h3 class="text-success">@Html.DisplayFor(model => model.MarketData.PriceChangePercentage30D)</h3>

                            }
                            <span>30d %</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            <h3>$@Html.DisplayName(Model.MarketData.MarketCap.GetValueOrDefault("usd").ToString())</h3>
                            <span>Market Cap</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            <h3>$@Html.DisplayName(Model.MarketData.MarketCapChange24HInCurrency.GetValueOrDefault("usd").ToString())</h3>
                            <span>Market Cap Change (24h)</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card mb-3 data-card">
            <div class="card-content">
                <div class="card-body">
                    <div class="media d-flex">
                        <div class="align-self-center">
                            <i class="icon-speech warning font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                            @if (Model.MarketData.MarketCapChangePercentage24H < 0)
                            {
                                <h3 class="text-danger">@Html.DisplayFor(model => model.MarketData.MarketCapChangePercentage24H)</h3>

                            }
                            else
                            {
                                <h3 class="text-success">@Html.DisplayFor(model => model.MarketData.MarketCapChangePercentage24H)</h3>

                            }
                            <span>Market Cap Change (24h %)</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Search" role="button" class="btn btn-dark">Back to Coin Search</a>
</div>

CryptoHubV2/CryptoHub/Views/Coin/Search.cshtml
@model IReadOnlyList<CoinGecko.Entities.Response.Coins.CoinList>;

@{
    ViewData["Title"] = "Search";
}

<div class="jumbotron text-center">
    <h1 class="display-4">Coin Search</h1>
    <p class="lead">Search for details of cryptocurrency.</p>
    <hr />
</div>

<div class="container d-flex justify-content-center mt-2">
    <form asp-controller="Coin" asp-action="Search" method="get">
        <div class="container d-flex justify-content-center flex-column gap-2">
            <input type="text" id="search-input" name="SearchString" placeholder="Search for a coin..." />
            <input type="submit" role="button" class="btn btn-dark" value="Search" />
        </div>
    </form>
</div>

<div class="container mt-2" style="max-height: 45vh; overflow-y: scroll; width: max-content;">
    <ul class="list-group">
        @foreach (var coin in Model)
        {
            <a class="text-dark" style="text-decoration: none;" asp-controller="Coin" asp-action="CoinData" asp-route-id="@coin.Id">
            <li class="list-group-item list-coin">
                    @Html.DisplayName(coin.Name)
                <span class="badge bg-dark rounded-pill">(@coin.Symbol)</span>
            </li>
            </a>
        }
    </ul>
</div>

CryptoHubV2/CryptoHub/Views/Coin/TrendingCoins.cshtml
@model CoinGecko.Entities.Response.Search.TrendingList;

@{
    ViewData["Title"] = "Trending Coins";
}

<div class="jumbotron text-center">
    <h1 class="display-4">Trending Coins</h1>
    <p class="lead">Top 3 cryptocurrencies searched by users on CoinGecko in the last 24 hours.</p>
    <hr />
</div>

<div class="d-flex gap-3 justify-content-center">
    @for (int i = 0; i < 3; i++)
    {
        <div class="card card-custom bg-white border-white border-0" style="width: 25%">
            @if (i == 0)
            {
                <div class="card-custom-img" style="background-color: gold;"></div>
            }
            else if (i == 1)
            {
                <div class="card-custom-img" style="background-color: silver;"></div>
            }
            else
            {
                <div class="card-custom-img" style="background-color: saddlebrown;"></div>
            }
            <div class="card-custom-avatar">
                <img class="img-fluid" src="@Model.TrendingItems[i].TrendingItem.Large" alt="Avatar" />
            </div>
            <div class="card-body" style="overflow-y: auto">
                <h4 class="card-title">@Html.DisplayName(Model.TrendingItems[i].TrendingItem.Name) (@Html.DisplayName(Model.TrendingItems[i].TrendingItem.Symbol))</h4>
                <hr>
                <p class="card-text">Market Rank: @Html.DisplayName(Model.TrendingItems[i].TrendingItem.MarketCapRank.ToString())</p>
                <p class="card-text">BTC Value: @Html.DisplayName(Model.TrendingItems[i].TrendingItem.PriceBtc.ToString())</p>
            </div>
            <!--<div class="card-footer" style="background: inherit; border-color: inherit;">
                <a href="#" class="btn btn-primary">Option</a>
            </div> -->
        </div>
    }
</div>

CryptoHubV2/CryptoHub/Views/Crypto/Index.cshtml
@model CoinGecko.Entities.Response.Coins.CoinFullDataById;

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div>
    <h4>Coin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Symbol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Symbol)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MarketData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MarketData)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CryptoHubV2/CryptoHub/Views/Crypto/Market.cshtml
@model List<CoinGecko.Entities.Response.Coins.CoinMarkets>;

@{
    ViewData["Title"] = "Market";
}

<div class="jumbotron text-center">
    <h1 class="display-4">Market</h1>
    <p class="lead">Cryptocurrency data live.</p>
    <hr />
</div>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Coin</th>
            <th scope="col">Price</th>
            <th class="text-success" scope="col">High 24h</th>
            <th class="text-danger" scope="col">Low 24h</th>
            <th scope="col">Market Cap</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var coin in Model)
        {
            <tr>
                <th scope="row">@Html.DisplayName(coin.MarketCapRank.ToString())</th>
                <td><img src="@coin.Image" style="height: 30px; width: 30px;"> <strong>@Html.DisplayName(coin.Name)</strong> (@Html.DisplayName(coin.Symbol.ToUpper()))</td>
                <td>$@Html.DisplayName(coin.CurrentPrice.ToString())</td>
                <td>$@Html.DisplayName(coin.High24H.ToString())</td>
                <td>$@Html.DisplayName(coin.Low24H.ToString())</td>
                <td>$@Html.DisplayName(coin.MarketCap.ToString())</td>
            </tr>
        }
    </tbody>
</table>

CryptoHubV2/CryptoHub/Views/Crypto/Portfolio.cshtml
@model CryptoHub.Models.Portfolio

@{
    ViewData["Title"] = "Portfolio";
}

<div class="jumbotron text-center">
    <h1 class="display-4">Personal Portfolio</h1>
    <p class="lead">Simluate your current, ideal or proposed portfolio and analyze its worth.</p>
    <hr />
</div>

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Cryptocurrencies
    </button>
    <ul class="dropdown-menu">
        @foreach (var crypto in Model.CryptoList)
        {
            <form method="post" asp-page-handler="GetCoinPriceByIdAsync(@crypto.Id)">
            <li><button class="dropdown-item" type="button">@Html.DisplayName(crypto.Name) (@Html.DisplayName(crypto.Symbol).ToUpper())</button></li>
            </form>
        }
    </ul>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Cryptocurrency</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value ($)</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
      <!-- razor stuff here for getting coin price.-->
        
        <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>xxx</td>
    </tr>
  </tbody>
</table>

CryptoHubV2/CryptoHub/Views/Crypto/Search.cshtml
@model IReadOnlyList<CoinGecko.Entities.Response.Coins.CoinList>;

@{
    ViewData["Title"] = "Crypto Search";
}

<div class="jumbotron text-center">
    <h1 class="display-4">Crypto Search</h1>
    <p class="lead">Search for details of any cryptocurrency.</p>
    <hr />
</div>

<div class="container d-flex justify-content-center mt-2">
    <form asp-controller="Crypto" asp-action="Search" method="get">
        <div class="container d-flex justify-content-center flex-column gap-2">
            <input type="text" id="search-input" name="SearchString" placeholder="search for crypto..." />
            <input type="submit" role="button" class="btn btn-dark" value="Search" />
        </div>
    </form>
</div>

<div class="container mt-2" style="max-height: 45vh; overflow-y: scroll; width: max-content;">
    <ul class="list-group">
        @foreach (var coin in Model)
        {
            <a class="text-dark" style="text-decoration: none;" asp-controller="Crypto" asp-action="CryptoData" asp-route-id="@coin.Id">
            <li class="list-group-item list-coin">
                    @Html.DisplayName(coin.Name)
                <span class="badge bg-dark rounded-pill">(@coin.Symbol)</span>
            </li>
            </a>
        }
    </ul>
</div>

CryptoHubV2/CryptoHub/Views/Crypto/TrendingCoins.cshtml
@model CoinGecko.Entities.Response.Search.TrendingList;

@{
    ViewData["Title"] = "Trending Coins";
}

<div class="jumbotron text-center">
    <h1 class="display-4">Trending Coins</h1>
    <p class="lead">Top 3 coins searched by users on CoinGecko in the last 24 hours.</p>
    <hr />
</div>

<div class="d-flex gap-3 justify-content-center">
    @for (int i = 0; i < 3; i++)
    {
        <div class="card card-custom bg-white border-white border-0" style="width: 25%">
            @if (i == 0)
            {
                <div class="card-custom-img" style="background-color: gold;"></div>
            }
            else if (i == 1)
            {
                <div class="card-custom-img" style="background-color: silver;"></div>
            }
            else
            {
                <div class="card-custom-img" style="background-color: saddlebrown;"></div>
            }
            <div class="card-custom-avatar">
                <img class="img-fluid" src="@Model.TrendingItems[i].TrendingItem.Large" alt="Avatar" />
            </div>
            <div class="card-body" style="overflow-y: auto">
                <h4 class="card-title">@Html.DisplayName(Model.TrendingItems[i].TrendingItem.Name) (@Html.DisplayName(Model.TrendingItems[i].TrendingItem.Symbol))</h4>
                <hr>
                <p class="card-text">Market Rank: @Html.DisplayName(Model.TrendingItems[i].TrendingItem.MarketCapRank.ToString())</p>
                <p class="card-text">BTC Value: @Html.DisplayName(Model.TrendingItems[i].TrendingItem.PriceBtc.ToString())</p>
            </div>
            <!--<div class="card-footer" style="background: inherit; border-color: inherit;">
                <a href="#" class="btn btn-primary">Option</a>
            </div> -->
        </div>
    }
</div>

CryptoHubV2/CryptoHub/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container my-5 hero">
    <div class="container col-xxl-8 px-5 py-5">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <h1 class="display-5 fw-bold lh-1 mb-3 text-light">Analyse <span class="text-warning">Crypto</span></h1>
                <p class="lead text-white">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
                <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                    <button type="button" class="btn btn-warning btn-lg px-4 me-md-2">Primary</button>
                </div>
            </div>
        </div>
    </div>
</div>

CryptoHubV2/CryptoHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CryptoHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CryptoHub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CryptoHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crypto" asp-action="Market">Live-Market</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crypto" asp-action="Trending">Trending</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crypto" asp-action="Search">Crypto-Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <button type="button" class="btn btn-warning btn-floating btn-lg rounded-circle" id="btn-back-to-top">
        &#x2191;
    </button>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CryptoHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>